---
# Custom vim plugins
custom_vim_plugins: |
      [[custom_plugins]]
      name = 'hashivim/vim-terraform'
      merged = 0

      [[custom_plugins]]
      name = 'hashivim/vim-vagrant'
      merged = 0

      [[custom_plugins]]
      name = 'puppetlabs/puppet-syntax-vim'
      merged = 0

      [[custom_plugins]]
      name = 'fatih/vim-go'
      merged = 0